### ISSUE TITLE
IndexError: too many indices for tensor of dimension 2

### ISSUE THREAD

**Issue by yilawu** [DocF/YOLOv3-Torch2TRT#8]
when I run the detect.py and set **TensorRT = True**
It went error.

> Traceback (most recent call last):
>   File "/home/tx2wry/PycharmProjects/yolov3_torch2trt/detect.py", line 190, in <module>
>     detections = non_max_suppression(detections, opt.conf_thres, opt.nms_thres, method=2)
>   File "/home/tx2wry/PycharmProjects/yolov3_torch2trt/utils/utils.py", line 254, in non_max_suppression
>     image_pred = image_pred[(-score).argsort()]
> IndexError: too many indices for tensor of dimension 2

**Comment by 2king2** [comment]
请问找到原因了么？我也遇到了这个问题

**Comment by ZichengDuan** [comment]
> 请问找到原因了么？我也遇到了这个问题

你好，请问解决了吗
